# Teams Configuration for Jira Issues Status Report Generator
# This file contains configuration for all teams that can generate status reports
# 
# Required fields:
# - jira_project_key: The Jira project key (extracted from team name, no brackets)
# - team_name: Full team name
# - presenter: Team EM
#
# Optional fields:
#
# - slide_id: Google Slides slide ID (to be filled manually after first slide generation for new teams)
# - image_link: Link to team image file (to be filled manually)

teams:
  # [PRD] Team Ahoy: [AHOY]
  AHOY:
    jira_project_key: "AHOY"
    team_name: "[PRD] Team Ahoy: [AHOY]"
    team_id: 5950
    presenter: "Timur Nugmanov"
    domain: "Identity & Access"
    slide_id: "id.slide_20250909_121125"
    image_link: ""

  # [PRD] The Bumblebees: [BBEE]
  # [PRD] Team Clippy: [CLIP]
  BBEE:
    jira_project_key: "BBEE"
    team_name: "[PRD] The Bumblebees - Clippy: [BBEE]"
    team_ids: 
    - 90301
    - 210775
    presenter: "Christian Bieneck"
    domain: "App Foundations"
    slide_id: "id.slide_20250909_155018"
    image_link: ""

  # Compliant Admin Platform: [CAP]
  CAP:
    jira_project_key: "CAP"
    team_name: "Team Compliant Admin Platform: [CAP]"
    team_id: 200771
    presenter: "Jonathan Stoye"
    domain: 
    slide_id: "id.g32b5d11736d_5_0"
    image_link: ""

  # [PRD] Team Content API: [CAPI]
  CAPI:
    jira_project_key: "CAPI"
    team_name: "[PRD] Team Content API: [CAPI]"
    team_id: 61505
    presenter: "Noel O'Flaherty"
    domain: "CDA/CPA/CMA/GraphQL APIs, Assets"
    slide_id: "id.g2e7564e189d_0_586"
    image_link: ""

  # [PRD] Isotopes: [CFISO]
  CFISO:
    jira_project_key: "CFISO"
    team_name: "[PRD] Team Isotopes: [CFISO]"
    team_id: 57210
    presenter: "Yiotis Kaltsikis"
    domain: "App Foundations"
    slide_id: "id.g369214abfc4_0_10"
    image_link: ""

  # [PRD] Team Clippy: [CLIP]
  #CLIP:
    #jira_project_key: "CLIP"
    #team_name: "[PRD] Team Clippy: [CLIP]"
    #team_id: 210775
    #presenter: "Christian Bieneck"
    #slide_id: "id.g3684ecb6890_0_0"
    #image_link: ""

  # [PRD] Team Content Storage: [CSTORE]
  CSTORE:
    jira_project_key: "CSTORE"
    team_name: "[PRD] Team Content Storage: [CSTORE]"
    team_id: 8032
    presenter: "Meike Pollakowski"
    domain: ""
    slide_id: "g36c8b2d0b60_0_0"
    image_link: ""


  # [PRD] Team Alpine (Developer Experience)
  DX:
    jira_project_key: "DX"
    team_name: "[PRD] Team Developer Experience (Alpine)"
    team_id: 205723
    presenter: "Morgan Whitney"
    domain: "Ecosystem"
    slide_id: "id.g36ec2456e65_0_10"
    image_link: ""

  # [PRD] Team Tundra (Extensibility)
  EXT:
    jira_project_key: "EXT"
    team_name: "[PRD] Team Extensibility (Tundra)"
    team_id: 5983
    presenter: "Morgan Whitney"
    domain: "Ecosystem"
    slide_id: "g21bb3c3ca71_44_0"
    image_link: ""

  # [PRD] Fusion: [FUS]
  COPS:
    jira_project_key: "COPS"
    team_name: "[PRD] Content Operations: [FUS]"
    team_id: 191503
    presenter: "Stephen Lloyd"
    domain: ""
    slide_id: "id.g2e7564e189d_0_625"
    image_link: ""

  # [PRD] Team Groot: [GROOT]
  GROOT:
    jira_project_key: "GROOT"
    team_name: "[PRD] Team Groot:[GROOT]"
    team_id: 52476
    presenter: "Liam Stokinger"
    domain: "Discoverability & Semantics"
    slide_id: "id.g2e7564e189d_0_599"
    image_link: ""

  # [PRD] Team Hejo: [HEJO]
  HEJO:
    jira_project_key: "HEJO"
    team_name: "[PRD] Team Hejo: [HEJO]"
    team_id: 5952
    presenter: "Jonathan Duarte"
    domain: "Monetization Infrastructure"
    slide_id: "id.g2ec5d2811d2_6_42"
    image_link: ""

  # [PRD] Team Taiga (Marketplace)
  INTEG:
    jira_project_key: "INTEG"
    team_name: "[PRD] Team Marketplace (Taiga)"
    team_id: 65807
    presenter: "Michael Kivisto"
    domain: "Ecosystem"
    slide_id: "g305cc313dc5_2_0"
    image_link: ""

  # [PRD] Team Kraken: [KRK]
  KRK:
    jira_project_key: "KRK"
    team_name: "[PRD] Team Kraken: [KRK]"
    team_id: 10781
    presenter: "Holger Strom"
    domain: "Content Storage Infra"
    slide_id: "id.g35015920ad0_53_25"
    image_link: ""

  # [PRD] Mechagodzilla: [MEC]
  MEC:
    jira_project_key: "MEC"
    team_name: "[PRD] Team Mechagodzilla: [MEC]"
    team_id: 80893
    presenter: "Michael Pearce"
    domain: "Engineering Productivity"
    slide_id: "id.g2ec5d2811d2_27_13"
    image_link: ""

  # [PRD] Team Mogwai: [MOGWAI]
  MOGWAI:
    jira_project_key: "MOGWAI"
    team_name: "[PRD] Team Mogwai: [MOGWAI]"
    team_id: 11200
    presenter: "Lewis Cowper"
    domain: "Infrastructure (Fleet & Edge ops)"
    slide_id: "id.g35015920ad0_53_39"
    image_link: ""

  # [PRD] Team Moi: [MOI]
  MOI:
    jira_project_key: "MOI"
    team_name: "[PRD] Team Moi: [MOI]"
    team_id: 5953
    presenter: "Dan Strydom"
    domain: "Platform Insights"
    slide_id: "id.g2f57620c5c0_13_7"
    image_link: ""

  # Picard: [PIC]
  PIC:
    jira_project_key: "PIC"
    team_name: "Team Picard: [PIC]"
    team_id: 184597
    presenter: "Christian Bieneck"
    domain: "App Foundations"
    slide_id: "id.g316d527e0e1_0_2"
    image_link: ""

  # [PRD] Sparks: [SPA]
  SPA:
    jira_project_key: "SPA"
    team_name: "[PRD] Team Sparks: [SPA]"
    team_id: 13877
    presenter: "Chirantan Rajhans"
    domain: "Studio"
    slide_id: "id.g369214abfc4_0_27"
    image_link: ""

  # [PRD] Tolkien: [TOL]
  TOL:
    jira_project_key: "TOL"
    team_name: "[PRD] Team Tolkien: [TOL]"
    team_id: 44743
    presenter: "Rafaela Felix"
    domain: "Authoring & Publishing"
    slide_id: "g36f16ad6077_0_0"
    image_link: ""

  # [PRD] UI Foundation: [UFO]
  UFO:
    jira_project_key: "UFO"
    team_name: "[PRD] Team UI Foundation:[UFO]"
    team_id: 5947
    presenter: "Jonathan Stoye"
    domain: " "
    slide_id: "id.g2d473010025_5_0"
    image_link: ""

  # [PRD] Ninetailed: [NT]
  NT:
    jira_project_key: "NT"
    team_name: "[PRD] Team Personalization:[NT]"
    team_id: 213625
    presenter: "Sebastian Mühr"
    domain: " "
    slide_id: "id.slide_20250918_160539"
    image_link: ""

  # [PRD] Experience Analytics: [EXA]
  EXA:
    jira_project_key: "EXA"
    team_name: "[PRD] Experience Analytics:[EXA]"
    team_id: 210691
    presenter: "Sebastian Mühr"
    domain: " "
    slide_id: "id.slide_20250918_161548"
    image_link: ""


  # Entity Architecture: [ARC]
  ARC:
    jira_project_key: "ARC"
    team_name: "Entity Architecture: [ARC]"
    team_ids: 
    - 213441
    - 213101
    presenter: "Stephen Lloyd"
    domain: "Connecting & Restructuring Content"
    slide_id: "id.slide_20250919_115038"
    image_link: ""

  # Bridge API: [BAPI]
  BAPI:
    jira_project_key: "BAPI"
    team_name: "Bridge API: [BAPI]"
    team_ids: 
    presenter: ""
    domain: ""
    slide_id: ""
    image_link: ""



